console.table([
  {operation: `parseInt('11', 2)`, result: parseInt('11', 2)},
  {operation: `parseInt('11', 8)`, result: parseInt('11', 8)},
  {operation: `parseInt('11', 16)`, result: parseInt('11', 16)},
  {operation: `parseInt(5, 10)`, result: parseInt(5, 10)},
  {operation: `parseInt('5', 10)`, result: parseInt('5', 10)},
  {operation: `parseInt('+5', 10)`, result: parseInt('+5', 10)},
  {operation: `parseInt('5mm', 10)`, result: parseInt('5mm', 10)},
  {operation: `parseInt('(5)', 10)`, result: parseInt('(5)', 10)},
  {operation: `parseInt('"5"', 10)`, result: parseInt('"5"', 10)},
  {operation: `parseInt('[5]', 10)`, result: parseInt('[5]', 10)},
  {operation: `parseInt('NaN', 10)`, result: parseInt('NaN', 10)},
  {operation: `parseInt(Infinity, 10)`, result: parseInt(Infinity, 10)},
  {operation: `parseInt('Infinity', 10)`, result: parseInt('Infinity', 10)},
  {operation: `parseInt('-Infinity', 10)`, result: parseInt('-Infinity', 10)},
  {operation: `parseInt(5.1, 10)`, result: parseInt(5.1, 10)},
  {operation: `parseInt(5.1 * 1e50, 10)`, result: parseInt(5.1 * 1e50, 10)},
  {operation: `parseInt(0.000000000005, 10)`, result: parseInt(0.000000000005, 10)},
  {operation: `parseInt(0.0000005, 10)`, result: parseInt(0.0000005, 10)},
  {operation: `parseInt(0.000005, 10)`, result: parseInt(0.000005, 10)},
  {operation: `parseInt('fF', 16)`, result: parseInt('fF', 16)},
  {operation: `parseInt('0xff', 16)`, result: parseInt('0xff', 16)},
  {operation: `parseInt('0xFf', 16)`, result: parseInt('0xFf', 16)},
  {operation: `parseInt('  0xFf   ', 16)`, result: parseInt('  0xFf   ', 16)},
  {operation: `parseInt('ff', 2)`, result: parseInt('ff', 2)},
  {operation: `parseInt('ff', 8)`, result: parseInt('ff', 8)},
  {operation: `parseInt('ff', 10)`, result: parseInt('ff', 10)},
  {operation: `parseInt('ff', 15)`, result: parseInt('ff', 15)},
  {operation: `parseInt('ff', 16)`, result: parseInt('ff', 16)},
  {operation: `parseInt('ff', 17)`, result: parseInt('ff', 17)},
  {operation: `parseInt('ff', 20)`, result: parseInt('ff', 20)},
  {operation: `parseInt('ff', 30)`, result: parseInt('ff', 30)},
  {operation: `parseInt('ff', 31)`, result: parseInt('ff', 31)},
  {operation: `parseInt('ff', 32)`, result: parseInt('ff', 32)},
  {operation: `parseInt('ff', 33)`, result: parseInt('ff', 33)},
  {operation: `parseInt('ff', 34)`, result: parseInt('ff', 34)},
  {operation: `parseInt('ff', 35)`, result: parseInt('ff', 35)},
  {operation: `parseInt('ff', 36)`, result: parseInt('ff', 36)},
  {operation: `parseInt('ff', 37)`, result: parseInt('ff', 37)},
]);

console.table([
  {operation: `parseFloat(3.14)`, result: parseFloat(3.14)},
  {operation: `parseFloat('3.14')`, result: parseFloat('3.14')},
  {operation: `parseFloat('314e-2')`, result: parseFloat('314e-2')},
  {operation: `parseFloat('3.14text')`, result: parseFloat('3.14text')},
  {operation: `parseFloat('0.0314E+2')`, result: parseFloat('0.0314E+2')},
  {operation: `parseFloat('5')`, result: parseFloat('5')},
  {operation: `parseFloat('5.0')`, result: parseFloat('5.0')},
  {operation: `parseFloat('5.0000000000000001')`, result: parseFloat('5.0000000000000001')},
  {operation: `parseFloat('5.1')`, result: parseFloat('5.1')},
  {operation: `parseFloat('5.000000000000001')`, result: parseFloat('5.000000000000001')},
  {operation: `parseFloat('100')`, result: parseFloat('100')},
  {operation: `parseFloat('-100')`, result: parseFloat('-100')},
  {operation: `parseFloat('+100')`, result: parseFloat('+100')},
  {operation: `parseFloat(5)`, result: parseFloat(5)},
  {operation: `parseFloat('5')`, result: parseFloat('5')},
  {operation: `parseFloat('+5')`, result: parseFloat('+5')},
  {operation: `parseFloat('5mm')`, result: parseFloat('5mm')},
  {operation: `parseFloat('(5)')`, result: parseFloat('(5)')},
  {operation: `parseFloat('"5"')`, result: parseFloat('"5"')},
  {operation: `parseFloat('[5]')`, result: parseFloat('[5]')},
  {operation: `parseFloat('NaN')`, result: parseFloat('NaN')},
  {operation: `parseFloat('Infinity')`, result: parseFloat('Infinity')},
  {operation: `parseFloat('-Infinity')`, result: parseFloat('-Infinity')},
]);
